#ifndef RX_DEFINITIONS_H_
#define RX_DEFINITIONS_H_

#define UNDEFINED -1
#define HEARTBEAT 0
#define PRESENCE 1
#define MOTION 2
#define PROXIMITY 3
#define SCENE_RESPONSE 4
#define BODY_MOVEMENT 5
#define INIT_COMPLETE 6
#define SENSITIVITY_RESPONSE 7
#define TIME_TO_NO_PERSON_STATE_RESPONSE 8
#define MOTION_INQUIRY 9
#define PRESENCE_INQUIRY 10
#define PROXIMITY_INQUIRY 11
#define RESET_RESPONSE 12
#define HEARTBEAT_INQUIRY 13
#define INIT_COMPLETE_RESPONSE 14
#define DISTANCE 15
#define ORIENTATION 16
#define BODY_MOVEMENT_INQUIRY 17
#define DISTANCE_INQUIRY 18
#define ORIENTATION_INQUIRY 19
#define HEARTRATE 20
#define HEARTRATE_WAVEFORM 21
#define HEARTRATE_INQUIRY 22
#define HEARTRATE_WAVEFORM_INQUIRY 23
#define OUT_OF_BOUNDS 24
#define OUT_OF_BOUNDS_INQUIRY 25
#define BREATHING 26
#define BREATHING_INQUIRY 27
#define BREATHING_INFO 28
#define BREATHING_INFO_INQUIRY 29
#define BREATHING_WAVEFORM 30
#define BREATHING_WAVEFORM_INQUIRY 31

#endif