#ifndef MRX_DEFINITIONS_H_
#define MRX_DEFINITIONS_H_

#define UNDEFINED -1
#define SOFTWARE_VERSION 0
#define ENVIRONMENTAL 1
#define BODY_MOVEMENT 2
#define PROXIMITY 3
#define HEARTBEAT 4
#define ABNORMAL_RESET 5
#define INIT_SUCCESS 6

#endif