substitutions:
  device_id: test-mmwave-mr24hpb1
  device_name: Test mmWave MR24HPB1
  header_frame: headers/mr24hpb1_frame.h
  header_sensor: headers/mr24hpb1.h
  uart_rx_pin: "16"
  uart_tx_pin: "17"

esphome:
  name: ${device_id}
  friendly_name: ${device_name}
  includes:
  - ${header_frame}
  - ${header_sensor}

logger:
  logs:
    sensor: INFO
  
uart:
  id: soft_uart2
  baud_rate:  9600
  rx_pin: ${uart_rx_pin}
  tx_pin: ${uart_tx_pin}

sensor:
  - platform: custom
    lambda: |-
      auto mr24hpb1 = new MR24HPB1(id(soft_uart2)); 
      App.register_component(mr24hpb1);
      return {mr24hpb1->presence_sensor, mr24hpb1->motion_sensor, mr24hpb1->proximity_sensor, mr24hpb1->body_sensor};
    sensors:
      - id: presence_sensor
        name: Internal Presense Sensor
        internal: true
        on_value:
          - binary_sensor.template.publish:
              id: presence_template
              state: !lambda return x > 0;
      - id: motion_sensor
        name: Internal Motion Sensor
        internal: true
        on_value:
          - binary_sensor.template.publish:
              id: motion_template
              state: !lambda return x > 0;
      - id: proximity_sensor
        name: Proximity
        state_class: measurement   
      - id: body_sensor
        name: Body Movement
        state_class: measurement   
        
binary_sensor:
  - id: presence_template
    platform: template
    name: Presence
    device_class: occupancy
  - id: motion_template
    platform: template
    name: Motion
    device_class: motion